// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HubSpotService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129112621_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("WebhookEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentFromSourceAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookEventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookHeaders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookObjectId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookObjectType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WebhookEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
